apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coraza-spoa.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.namespaceOverride }}
  labels:
    {{- include "coraza-spoa.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
  before.conf: |
    {{- .Values.rules.before | trim | nindent 4 }}
  after.conf: |
    {{- .Values.rules.after | trim | nindent 4 }}
  extra.conf: |
    {{- .Values.rules.extra | trim | nindent 4 }}
